pub(crate) fn print_help() {
    println!("nando-cli");
    println!();
    println!("Commands:");
    println!("  status    Print the current Nando Wave workspace status");
    println!("  organ128-plan");
    println!("            Print the T480 cache-aware Organ128 cell plan");
    println!("  organ128-train-generate [seed] [epochs] [prompt] [generate-len]");
    println!("            Train the first Organ128 byte readout and generate text");
    println!("  organ128-dialog-generate [seed] [prompt]");
    println!("            Answer from the bilingual prompt-wave dialog corpus");
    println!("  organ128-settle-dialog [seed] [prompt] [ticks]");
    println!("            Answer after Organ128 CarrierWave/WaveBus settle ticks with controls");
    println!("  organ128-wave-scorer-eval [seed] [epochs] [ticks]");
    println!("            Train/eval a tiny wave-state scorer over the dialog corpus");
    println!("  organ128-response-gate-eval [seed] [ticks]");
    println!("            Check answer/refuse gating on known prompts and noise prompts");
    println!("  organ128-thought-probe-eval [seed] [ticks] [epochs]");
    println!("            Train/eval a tiny dynamic-state probe over ThoughtState only");
    println!("  organ128-modadd-eval [seed] [modulus] [train-cases] [holdout-cases]");
    println!("            Run the GOAL v0 modular-addition evidence-package probe");
    println!("  organ128-modadd-seed-sweep [modulus] [train-cases] [holdout-cases]");
    println!("            Sweep the GOAL v0 modular-addition probe over fixed seeds");
    println!("  wave-tick <input-byte> [seed]");
    println!("            Run one deterministic Stage 2 wave tick");
    println!("  snapshot-save <input-byte> [seed] [path]");
    println!("            Save a Stage 2 .nws1 snapshot");
    println!("  snapshot-read <path>");
    println!("            Read a Stage 2 .nws1 snapshot");
    println!("  bench-stage2-tick [seed] [ticks]");
    println!("            Measure seed tick vs precomputed Stage2Organ tick speed");
    println!("  bench-link-tissue [seed] [ticks]");
    println!("            Measure Cell32 score vs pair/triple LinkTissue score loops");
    println!("  live-byte-train [seed] <text...>");
    println!("            Run primitive online byte prediction with local feedback");
    println!("  live-byte-learn [seed] <text...>");
    println!("            Train tiny online next-byte adapter from wave traces");
    println!("  live-byte-holdout [seed] <text...>");
    println!("            Train tiny byte adapter on first half and test second half");
    println!("  live-byte-holdout-suite [seed]");
    println!("            Run live byte holdout gates over built-in corpora");
    println!("  live-byte-holdout-seed-sweep");
    println!("            Sweep live byte holdout suite over fixed seeds");
    println!("  live-cell-promote [seed] <text...>");
    println!(
        "            Test candidate -> holdout gate -> promoted/rejected Cell32 learner state"
    );
    println!("  live-architecture-compare [seed]");
    println!("            Compare 3x/6x Cell32 local learners against mono96/mono192 controls");
    println!("  live-tissue-diagnose [seed]");
    println!("            Diagnose pair/triple LinkTissue gains, ablations, and typed topology");
    println!("  live-grok-trace [seed] [epochs] [interval]");
    println!("            Trace early grokking progress measures for LinkTissue");
    println!("  live-grok-sweep [epochs] [interval]");
    println!("            Compare LinkTissue update rules over fixed grokking seeds");
    println!("  eval-one-tick <input-byte> [seed]");
    println!("            Print a minimal Stage 2 one-tick eval report");
    println!("  eval-periodic [seed] [cases] [start] [step]");
    println!("            Run the first Stage 3 periodic baseline eval");
    println!("  eval-phase-composition [seed] [cases] [start] [input-step] [phase-step]");
    println!("            Run a synthetic phase-composition baseline eval");
    println!("  eval-phase-holdout [train-seed] [holdout-seed] [cases]");
    println!("            Check the phase-composition candidate on a holdout split");
    println!("  eval-carrier-control [train-seed] [holdout-seed] [cases]");
    println!("            Compare correct, missing, wrong, and corrupted CarrierWave");
    println!("  eval-bus-transfer [train-seed] [holdout-seed] [cases]");
    println!("            Test CarrierWave effect through WaveBus center phase only");
    println!("  eval-snapshot-memory [train-seed] [holdout-seed] [cases]");
    println!("            Test serialized snapshot replay against cold/wrong/corrupted state");
    println!("  eval-snapshot-transition [train-seed] [holdout-seed] [cases]");
    println!("            Test previous snapshot offset as a next-state transition predictor");
    println!("  eval-snapshot-dynamics [train-seed] [holdout-seed] [cases]");
    println!("            Test snapshot transition over a smooth CarrierWave sequence");
    println!("  eval-snapshot-multitick [train-seed] [holdout-seed] [cases]");
    println!("            Test one warm snapshot across several smooth CarrierWave ticks");
    println!("  eval-snapshot-adapt [train-seed] [holdout-seed] [cases]");
    println!("            Test online phase correction from feedback after warm snapshot");
    println!("  eval-snapshot-decoder [train-seed] [holdout-seed] [cases]");
    println!("            Test an online transition decoder with snapshot features");
    println!("  eval-snapshot-keyed [train-seed] [holdout-seed] [cases]");
    println!("            Test snapshot-private state against no-snapshot controls");
    println!("  eval-snapshot-keyed-transition [train-seed] [holdout-seed] [cases]");
    println!("            Test future wave-state combined with snapshot-private state");
    println!("  eval-snapshot-noisy-keyed-transition [train-seed] [holdout-seed] [cases]");
    println!("            Test noisy future transition with hidden snapshot modulation");
    println!("  eval-snapshot-noisy-keyed-transition-sweep [train-seed] [holdout-seed] [cases]");
    println!("            Sweep noisy snapshot transition over several horizons");
    println!("  eval-snapshot-noisy-keyed-transition-seed-sweep [cases]");
    println!("            Sweep noisy snapshot transition over fixed seed pairs");
    println!("  eval-byte-context [train-seed] [holdout-seed] [cases]");
    println!("            Train and test the first byte-stream context probe");
    println!("  eval-byte-context-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Train frozen byte-context prototypes and test holdout");
    println!("  eval-byte-context-offset-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test offset-only byte-context centroid prototypes");
    println!("  eval-byte-context-denoised-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test offset plus top-sin byte-context centroid prototypes");
    println!("  eval-byte-context-relative-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test seed-normalized relative byte-context centroid prototypes");
    println!("  eval-byte-context-lexical-carrier-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test lexical CarrierWave state formation for byte-context prototypes");
    println!("  eval-byte-context-cellular-carrier-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test task-cell CarrierWave lock for byte-context prototypes");
    println!("  eval-byte-context-trained-carrier-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test supervised harmonic CarrierWave lock cells");
    println!("  eval-byte-context-prompt-carrier-centroid [train-seed] [holdout-seed] [cases]");
    println!("            Test full-prompt harmonic CarrierWave lock cells");
    println!(
        "  eval-byte-context-prompt-carrier-diverse-centroid [train-seed] [holdout-seed] [cases]"
    );
    println!("            Test full-prompt lock cells across diverse prompt templates");
    println!("  eval-byte-context-centroid-seed-sweep [cases]");
    println!("            Sweep byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-offset-centroid-seed-sweep [cases]");
    println!("            Sweep offset-only byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-denoised-centroid-seed-sweep [cases]");
    println!("            Sweep denoised byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-relative-centroid-seed-sweep [cases]");
    println!("            Sweep relative byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-lexical-carrier-centroid-seed-sweep [cases]");
    println!("            Sweep lexical CarrierWave byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-cellular-carrier-centroid-seed-sweep [cases]");
    println!("            Sweep cellular CarrierWave byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-trained-carrier-centroid-seed-sweep [cases]");
    println!("            Sweep trained CarrierWave byte-context centroid over fixed seed pairs");
    println!("  eval-byte-context-prompt-carrier-centroid-seed-sweep [cases]");
    println!(
        "            Sweep prompt-cloud CarrierWave byte-context centroid over fixed seed pairs"
    );
    println!("  eval-byte-context-prompt-carrier-diverse-centroid-seed-sweep [cases]");
    println!("            Sweep diverse prompt-cloud centroid over fixed seed pairs");
    println!("  eval-byte-context-centroid-ablation [train-seed] [holdout-seed] [cases]");
    println!("            Ablate byte-context centroid snapshot features");
    println!("  eval-byte-context-cellular-carrier-ablation [train-seed] [holdout-seed] [cases]");
    println!("            Ablate cellular CarrierWave lock cells");
    println!("  eval-byte-context-trained-carrier-ablation [train-seed] [holdout-seed] [cases]");
    println!("            Ablate trained CarrierWave lock cells");
    println!("  eval-byte-context-prompt-carrier-ablation [train-seed] [holdout-seed] [cases]");
    println!("            Ablate prompt-cloud CarrierWave lock cells");
    println!(
        "  eval-byte-context-prompt-carrier-diverse-ablation [train-seed] [holdout-seed] [cases]"
    );
    println!("            Ablate diverse prompt-cloud CarrierWave lock cells");
    println!("  eval-chat0 [train-seed] [holdout-seed] [cases]");
    println!("            Run the first short-response Chat-0 loop with feedback logging");
    println!("  eval-settle-word [train-seed] [holdout-seed] [cases]");
    println!("            Test short-word readout after multi-tick Organ192 settling");
    println!("  eval-settle-word-seed-sweep [cases]");
    println!("            Sweep gated short-word settling across fixed seed pairs");
    println!("  eval-chat0-route [train-seed] [holdout-seed] [cases]");
    println!("            Measure manual Chat-0 route quality on free prompt templates");
    println!("  eval-chat0-promote [feedback-log] [train-seed] [holdout-seed] [cases]");
    println!("            Test logged feedback as an eval-gated replay promotion candidate");
    println!("  eval-chat0-promoted-holdout [feedback-log] [train-seed] [holdout-seed] [cases]");
    println!("            Test whether promoted feedback transfers beyond exact prompt replay");
    println!(
        "  chat0-promote-save <feedback-log> <state-path> [train-seed] [holdout-seed] [cases]"
    );
    println!("            Save a promoted feedback state only after the promote eval passes");
    println!("  chat0-once <prompt> [expected] [trace-path]");
    println!("            Generate one Chat-0 answer and save trace/feedback files");
    println!("  chat0-once-promoted <state-path> <prompt> [expected] [trace-path]");
    println!("            Generate one Chat-0 answer with an eval-promoted state overlay");
    println!("  chat0-shell [trace-dir] [feedback-log]");
    println!("            Read prompts from stdin and write trace per answer");
}
